{"sid": "456030cd5bde48b7b5d851864f59a969", "uid": null, "qid": "365c3dc64f464e1181afcd0375f8999c", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [365c3dc64f464e1181afcd0375f8999c]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 89, in execute\n    Agent.Init(OpenfabricGenerator())\n  File \"/openfabric/app/Agent/agent.py\", line 28, in Init\n    VectorDB.INIT()\n  File \"/openfabric/app/Agent/Storage/VectorDB.py\", line 14, in INIT\n    cls.init_table()\n  File \"/openfabric/app/Agent/Storage/VectorDB.py\", line 54, in init_table\n    cls.cur.execute(\"\"\"\npsycopg2.errors.SyntaxError: syntax error at or near \"embedding\"\nLINE 8:             embedding VECTOR(384)\n                    ^\n\n", "created_at": "2025-06-29T05:39:51.319812"}], "status": "FAILED", "created_at": "2025-06-29T05:39:45.819149", "updated_at": "2025-06-29T05:39:51.319876", "finished": true}