{"sid": "57d4605bde8a42a0a585fed2ac86e88f", "uid": null, "qid": "04ed89bb3b974fddabb9e935d6e32563", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [04ed89bb3b974fddabb9e935d6e32563]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 94, in execute\n    agent = Agent('gemini',session_id)\n  File \"/openfabric/app/Agent/agent.py\", line 38, in __init__\n    self.init_baseLLM(baseLLM)\n  File \"/openfabric/app/Agent/agent.py\", line 64, in init_baseLLM\n    self.llm:LLM = GeminiLLM(history)\n  File \"/openfabric/app/Agent/LLM/Gemini.py\", line 17, in __init__\n    for item in history:\nTypeError: 'NoneType' object is not iterable\n", "created_at": "2025-06-28T13:26:37.600111"}], "status": "FAILED", "created_at": "2025-06-28T13:26:30.363788", "updated_at": "2025-06-28T13:26:37.600131", "finished": true}