{"sid": "b699db0ea0bf4bae866e4e0c5ffa82ab", "uid": null, "qid": "1378f688dc064a92837d7a2d11d8159f", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [1378f688dc064a92837d7a2d11d8159f]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 104, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/Agent.py\", line 62, in Exec\n    agent_response = self.exec(prompt)\n  File \"/openfabric/app/Agent/Agent.py\", line 79, in exec\n    PROCESSOR = Processor(\nTypeError: __init__() got an unexpected keyword argument 'llm_response'\n", "created_at": "2025-07-01T05:04:15.136238"}], "status": "FAILED", "created_at": "2025-07-01T05:04:08.794020", "updated_at": "2025-07-01T05:04:15.136264", "finished": true}