{"sid": "17fd2815b5d84a84a5040774bbd650c7", "uid": null, "qid": "de897401e26547249a1ad72917cafc85", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [de897401e26547249a1ad72917cafc85]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 90, in execute\n    generator = OpenfabricGenerator.get_generator(app_ids=app_ids)\n  File \"/openfabric/app/main.py\", line 44, in get_generator\n    if cls._generator:\nAttributeError: type object 'OpenfabricGenerator' has no attribute '_generator'\n", "created_at": "2025-06-30T09:43:29.759184"}], "status": "FAILED", "created_at": "2025-06-30T09:43:21.862448", "updated_at": "2025-06-30T09:43:29.759207", "finished": true}