{"sid": "7466f4e8473b41bc89cf2240df92427f", "uid": null, "qid": "4d29eb7f732b40809d9e3b09dcd36505", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [4d29eb7f732b40809d9e3b09dcd36505]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 92, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 72, in Exec\n    text = self.process(response)\n  File \"/openfabric/app/Agent/agent.py\", line 118, in process\n    self.exit(parsed)\n  File \"/openfabric/app/Agent/agent.py\", line 85, in exit\n    Agent.db.save_session(self.session_id,self.username,resp['summary'],Agent.sessions[self.session_id])\nKeyError: 'summary'\n", "created_at": "2025-06-28T18:55:09.808278"}], "status": "FAILED", "created_at": "2025-06-28T18:54:49.493903", "updated_at": "2025-06-28T18:55:09.809105", "finished": true}