{"sid": "5881ab57d59c43739a81d22053ff312e", "uid": null, "qid": "47f9f97ffe954690834cb31e7e824f80", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [47f9f97ffe954690834cb31e7e824f80]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 92, in execute\n    agent = Agent('gemini',\"TEST_USER\",session_id ,generator)\n  File \"/openfabric/app/Agent/agent.py\", line 38, in __init__\n    self.init_baseLLM(baseLLM)\n  File \"/openfabric/app/Agent/agent.py\", line 43, in init_baseLLM\n    history = Agent._sessionsManager.get_session_history(self.session_data.session_id)\n  File \"/openfabric/app/Agent/agent.py\", line 280, in get_session_history\n    if session_id in cls.sessions:\nAttributeError: type object 'SessionManager' has no attribute 'sessions'\n", "created_at": "2025-06-30T10:07:16.849302"}], "status": "FAILED", "created_at": "2025-06-30T10:07:11.873077", "updated_at": "2025-06-30T10:07:16.849317", "finished": true}