{"sid": "645e70b48465403283e39dff8e47818d", "uid": null, "qid": "16617fb8acdd400f92eec96ddf86dc65", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [16617fb8acdd400f92eec96ddf86dc65]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 93, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 53, in Exec\n    agent_response = self.exec(prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 74, in exec\n    db =Agent.db )\nAttributeError: type object 'Agent' has no attribute 'db'\n", "created_at": "2025-06-30T10:14:41.732800"}], "status": "FAILED", "created_at": "2025-06-30T10:14:30.143265", "updated_at": "2025-06-30T10:14:41.732830", "finished": true}