{"sid": "29e6738e29204618947ce292e5d04136", "uid": null, "qid": "cfa9022b2f4545dcabc01a40aec9e397", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [cfa9022b2f4545dcabc01a40aec9e397]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 92, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 83, in Exec\n    self.EXIT()\n  File \"/openfabric/app/Agent/agent.py\", line 102, in EXIT\n    Agent.db.save_session(self.session_id,self.username,self.exit_summary,Agent.sessions[self.session_id])\n  File \"/openfabric/app/Agent/Storage/VectorDB.py\", line 65, in save_session\n    self.save(session_id=session_id ,username = username ,summary=summary)\n  File \"/openfabric/app/Agent/Storage/VectorDB.py\", line 33, in save\n    self.cur.execute(\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"chat_index_session_id_key\"\nDETAIL:  Key (session_id)=(89c2dd30-be36-4c97-bc56-cd23894d8084) already exists.\n\n", "created_at": "2025-06-29T08:12:43.302815"}], "status": "FAILED", "created_at": "2025-06-29T08:12:41.403425", "updated_at": "2025-06-29T08:12:43.302872", "finished": true}