{"sid": "2ab4ceffd7914b838e2bdb3dbf1cea46", "uid": null, "qid": "ee02a858355442c78214d97147b85f32", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [ee02a858355442c78214d97147b85f32]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 92, in execute\n    agent = Agent('gemini',\"TEST_USER\",session_id ,generator)\n  File \"/openfabric/app/Agent/agent.py\", line 36, in __init__\n    self.init_baseLLM(baseLLM)\n  File \"/openfabric/app/Agent/agent.py\", line 42, in init_baseLLM\n    history = Agent._sessionsManager.get_session_history(self.session_id)\nAttributeError: 'Agent' object has no attribute 'session_id'\n", "created_at": "2025-06-30T09:59:20.377991"}], "status": "FAILED", "created_at": "2025-06-30T09:59:10.106562", "updated_at": "2025-06-30T09:59:20.378033", "finished": true}