{"sid": "8ee5a8c6ea714c438e6283313f20c128", "uid": null, "qid": "49247f9f870345f6a668507a60b0e7d2", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [49247f9f870345f6a668507a60b0e7d2]\nTraceback (most recent call last):\n  File \"/openfabric/app/Agent/Storage/VectorDB.py\", line 113, in save_session\n    conn = cls.get_con()\nAttributeError: type object 'VectorStore' has no attribute 'get_con'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 93, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 66, in Exec\n    self.EXIT()\n  File \"/openfabric/app/Agent/agent.py\", line 97, in EXIT\n    Agent._sessionsManager.save_session(\n  File \"/openfabric/app/Agent/agent.py\", line 305, in save_session\n    cls.db.save_session(username=username, session_id=session_id,image_desc=image_desc,history=cls._sessions[session_id],summary=summary)\n  File \"/openfabric/app/Agent/Storage/VectorDB.py\", line 38, in save_session\n    cls._vectorStore.save_session(session_id=session_id ,username = username ,summary=summary)\n  File \"/openfabric/app/Agent/Storage/VectorDB.py\", line 125, in save_session\n    cls._pool.putconn(conn)\nUnboundLocalError: local variable 'conn' referenced before assignment\n", "created_at": "2025-06-30T10:44:44.004502"}], "status": "FAILED", "created_at": "2025-06-30T10:44:25.069095", "updated_at": "2025-06-30T10:44:44.004547", "finished": true}