{"sid": "05a2e7e39b23476a9b62655fc165d58f", "uid": null, "qid": "7fea8f1d16fe45c19a4794a7eb210191", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [7fea8f1d16fe45c19a4794a7eb210191]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 92, in execute\n    agent = Agent('gemini',\"TEST_USER\",session_id ,generator)\n  File \"/openfabric/app/Agent/agent.py\", line 36, in __init__\n    self.init_baseLLM(baseLLM)\n  File \"/openfabric/app/Agent/agent.py\", line 42, in init_baseLLM\n    history = Agent._sessionsManager.get_session_history(self.session_data.session_id)\nAttributeError: 'Agent' object has no attribute 'session_data'\n", "created_at": "2025-06-30T10:06:06.040371"}], "status": "FAILED", "created_at": "2025-06-30T10:06:00.656146", "updated_at": "2025-06-30T10:06:06.040388", "finished": true}