{"sid": "1e87006ae3914af88a5041a91a5aea49", "uid": null, "qid": "9e52f1d3dca04bcd9aa2b1e1c29128d8", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [9e52f1d3dca04bcd9aa2b1e1c29128d8]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 91, in execute\n    agent = Agent('gemini',\"TEST_USER\",session_id )\n  File \"/openfabric/app/Agent/agent.py\", line 38, in __init__\n    self.init_baseLLM(baseLLM)\n  File \"/openfabric/app/Agent/agent.py\", line 65, in init_baseLLM\n    self.llm:LLM = GeminiLLM(history)\n  File \"/openfabric/app/Agent/LLM/Gemini.py\", line 17, in __init__\n    for item in history:\nTypeError: 'NoneType' object is not iterable\n", "created_at": "2025-06-29T05:11:34.009119"}], "status": "FAILED", "created_at": "2025-06-29T05:11:33.643163", "updated_at": "2025-06-29T05:11:34.009150", "finished": true}